- name: Install Graphite Dependencies
  apt: "name={{ item }} state=latest"
  with_items:
    - sqlite
    - python-pysqlite2
    - python-pip
    - python-cairo
    - python-dev
    - python-django

- name: install whisper
  command: pip install whisper

- name: install carbon
  command: pip install carbon

- name: install graphite-web
  command: pip install graphite-web

- name: Generate random secret key
  shell: tr -dc A-Za-z0-9_ < /dev/urandom | head -c 64; echo creates=/opt/graphite/webapp/graphite/local_settings.py
  register: SECRET_KEY

- name: Configure Graphite webapp
  template: src=opt/graphite/webapp/graphite/local_settings.py.j2 dest=/opt/graphite/webapp/graphite/local_settings.py mode=0644
  when: SECRET_KEY.skipped is not defined
  notify:
    - reload httpd

- name: Setup sqlite DB
  command: /usr/bin/python manage.py syncdb --noinput chdir=/opt/graphite/webapp/graphite creates=/opt/graphite/storage/graphite.db
